In [ ]:
import pandas as pd

In [ ]:
dados = pd.read_csv('/content/Customer-Churn.csv')

In [ ]:
dados.shape

(7043, 18)

In [ ]:
dados.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

In [ ]:
traducao_dic = {"Sim" : 1,
                "Nao" : 0}
dadosmodificados = dados[['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']].replace(traducao_dic)
dadosmodificados.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [ ]:
dummie_dados = pd.get_dummies(dados.drop(['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'], axis = 1))

dados_final = pd.concat([dadosmodificados, dummie_dados], axis = 1)

In [ ]:
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                        False   
1               34        56.95                         True   
2                2        53.85                         True   
3               45        42.30                        False   
4                2        70.70                         True   

   VariasLinhasTelefonicas_SemServicoTelefonico  ...  StreamingDeFilmes_Nao  \
0                                          True  ...                   True   
1                                         False  ...                   True   
2                                         False  ...                   True   
3                                          True  ...                   True   
4                                         False  ...                   True   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                   False                  False   
1                                   False                  False   
2                                   False                  False   
3                                   False                  False   
4                                   False                  False   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                    False                        True                 False   
1                    False                       False                  True   
2                    False                        True                 False   
3                    False                       False                  True   
4                    False                        True                 False   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                             False                            True   
1                             False                           False   
2                             False                           False   
3                             False                           False   
4                             False                            True   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                         False                           False  
1                          True                           False  
2                          True                           False  
3                         False                            True  
4                         False                           False  

[5 rows x 39 columns]

In [ ]:
pd.set_option('display.max_columns', 39)


In [ ]:
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                        False   
1               34        56.95                         True   
2                2        53.85                         True   
3               45        42.30                        False   
4                2        70.70                         True   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim  \
0                                          True                        False   
1                                         False                        False   
2                                         False                        False   
3                                          True                        False   
4                                         False                        False   

   ServicoDeInternet_DSL  ServicoDeInternet_FibraOptica  \
0                   True                          False   
1                   True                          False   
2                   True                          False   
3                   True                          False   
4                  False                           True   

   ServicoDeInternet_Nao  SegurancaOnline_Nao  \
0                  False                 True   
1                  False                False   
2                  False                False   
3                  False                False   
4                  False                 True   

   SegurancaOnline_SemServicoDeInternet  SegurancaOnline_Sim  \
0                                 False                False   
1                                 False                 True   
2                                 False                 True   
3                                 False                 True   
4                                 False                False   

   BackupOnline_Nao  BackupOnline_SemServicoDeInternet  BackupOnline_Sim  \
0             False                              False              True   
1              True                              False             False   
2             False                              False              True   
3              True                              False             False   
4              True                              False             False   

   SeguroNoDispositivo_Nao  SeguroNoDispositivo_SemServicoDeInternet  \
0                     True                                     False   
1                    False                                     False   
2                     True                                     False   
3                    False                                     False   
4                     True                                     False   

   SeguroNoDispositivo_Sim  SuporteTecnico_Nao  \
0                    False                True   
1                     True                True   
2                    False                True   
3                     True               False   
4                    False                True   

   SuporteTecnico_SemServicoDeInternet  SuporteTecnico_Sim  TVaCabo_Nao  \
0                                False               False         True   
1                                False               False         True   
2                                False               False         True   
3                                False                True         True   
4                                False               False         

In [ ]:
Xmaria = [[0,0,1,1,0,0,39.90,1,0,0,0,1,0,1,0,0,0,0,1,1,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,1]]

In [ ]:
Xmaria

[[0,
  0,
  1,
  1,
  0,
  0,
  39.9,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1]]

In [ ]:
x = dados_final.drop('Churn', axis = 1)
y = dados_final['Churn']

In [ ]:
from imblearn.over_sampling import SMOTE
smt = SMOTE(random_state=123)
x, y = smt.fit_resample(x, y)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
norm = StandardScaler()

X_normalizado = norm. fit_transform(x)
X_normalizado

array([[ 1.26542767, -0.52771004, -3.06083934, ...,  1.05423234,
        -0.54757347, -0.5315994 ],
       [-0.79024667, -0.52771004,  0.32670777, ..., -0.9485575 ,
         1.82623896, -0.5315994 ],
       [-0.79024667, -0.52771004,  0.32670777, ..., -0.9485575 ,
         1.82623896, -0.5315994 ],
       ...,
       [-0.79024667, -0.52771004,  0.32670777, ...,  1.05423234,
        -0.54757347, -0.5315994 ],
       [-0.79024667, -0.52771004,  0.32670777, ..., -0.9485575 ,
        -0.54757347, -0.5315994 ],
       [-0.79024667, -0.52771004,  0.32670777, ..., -0.9485575 ,
        -0.54757347, -0.5315994 ]])

In [ ]:
X_normalizado[0]

array([ 1.26542767, -0.52771004, -3.06083934,  0.81482091, -0.41318358,
       -1.10771815, -1.3217706 , -0.99594945,  3.06083934, -0.93594717,
        1.48315631, -1.05853285, -0.44850949,  0.77803383, -0.44850949,
       -0.59639952, -1.09729069, -0.44850949,  1.35121363,  0.91935908,
       -0.44850949, -0.73960631,  0.7857356 , -0.44850949, -0.60652979,
        1.08898545, -0.44850949, -0.84638695,  1.10588699, -0.44850949,
       -0.85787548, -0.4605816 ,  0.68807296, -0.47286547, -0.50790015,
        1.05423234, -0.54757347, -0.5315994 ])

In [ ]:
Xmaria_normalizado = norm.transform(pd.DataFrame(Xmaria, columns = x.columns))
Xmaria_normalizado

array([[-0.79024667, -0.52771004,  0.32670777,  0.81482091, -0.41318358,
        -1.14938255, -0.97236043,  1.00406703, -0.32670777, -0.93594717,
        -0.67423777,  0.94470379, -0.44850949,  0.77803383, -0.44850949,
        -0.59639952, -1.09729069, -0.44850949,  1.35121363,  0.91935908,
         2.22960721, -0.73960631, -1.27269275,  2.22960721, -0.60652979,
         1.08898545, -0.44850949, -0.84638695, -0.90425153, -0.44850949,
         1.16567033, -0.4605816 , -1.45333425,  2.1147664 , -0.50790015,
        -0.9485575 , -0.54757347,  1.88111576]])

In [ ]:
import numpy as np

In [ ]:
a = Xmaria_normalizado

In [ ]:
b = X_normalizado[0]

In [ ]:
a - b

array([[-2.05567434,  0.        ,  3.38754711,  0.        ,  0.        ,
        -0.0416644 ,  0.34941017,  2.00001647, -3.38754711,  0.        ,
        -2.15739408,  2.00323664,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         2.6781167 ,  0.        , -2.05842835,  2.6781167 ,  0.        ,
         0.        ,  0.        ,  0.        , -2.01013852,  0.        ,
         2.02354582,  0.        , -2.14140721,  2.58763186,  0.        ,
        -2.00278985,  0.        ,  2.41271515]])

In [ ]:
np.square(a-b)

array([[4.22579699e+00, 0.00000000e+00, 1.14754754e+01, 0.00000000e+00,
        0.00000000e+00, 1.73592202e-03, 1.22087466e-01, 4.00006590e+00,
        1.14754754e+01, 0.00000000e+00, 4.65434920e+00, 4.01295706e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        7.17230906e+00, 0.00000000e+00, 4.23712727e+00, 7.17230906e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.04065686e+00, 0.00000000e+00, 4.09473767e+00, 0.00000000e+00,
        4.58562485e+00, 6.69583866e+00, 0.00000000e+00, 4.01116717e+00,
        0.00000000e+00, 5.82119441e+00]])

In [ ]:
np.sum(np.square(a-b))

87.79890842414623

In [ ]:
np.sqrt(84.07574038273466)

9.169282435541762

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X_normalizado, y, test_size = 0.3, random_state=123)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier(metric = 'euclidean')

In [ ]:
knn.fit(X_treino, y_treino)

KNeighborsClassifier(metric='euclidean')

In [ ]:
predito_knn = knn.predict(X_teste)

In [ ]:
predito_knn

array([1, 0, 0, ..., 0, 1, 1])

In [ ]:
def calcula_distancia(dados_clientes, dados_maria, numero_clientes):
    distancias = []

    for i in range(numero_clientes):
        dist1 = dados_maria - dados_clientes[i]
        soma_quadrado = np.sum(np.square(dist1))
        distancias.append(np.sqrt(soma_quadrado))

    return distancias

In [ ]:
calcula_distancia(X_normalizado, Xmaria_normalizado, 10)

[9.37010717250055,
 8.92215193643032,
 8.233388169361287,
 9.854580807577186,
 7.575793888524783,
 8.780238370501579,
 8.703385792459425,
 10.36213425141941,
 9.175687760286849,
 7.863871468693277]

In [ ]:
X_treino

array([[-0.79024667, -0.52771004, -3.06083934, ..., -0.9485575 ,
         1.82623896, -0.5315994 ],
       [ 1.26542767,  1.89498006,  0.32670777, ..., -0.9485575 ,
         1.82623896, -0.5315994 ],
       [-0.79024667, -0.52771004,  0.32670777, ...,  1.05423234,
        -0.54757347, -0.5315994 ],
       ...,
       [ 1.26542767,  1.89498006,  0.32670777, ..., -0.9485575 ,
         1.82623896, -0.5315994 ],
       [ 1.26542767,  1.89498006,  0.32670777, ...,  1.05423234,
        -0.54757347, -0.5315994 ],
       [-0.79024667, -0.52771004,  0.32670777, ...,  1.05423234,
        -0.54757347, -0.5315994 ]])

In [ ]:
y_treino

4831    0
5077    0
9023    1
4424    1
5236    0
       ..
9785    1
7763    1
5218    0
1346    1
3582    0
Name: Churn, Length: 7243, dtype: int64

In [ ]:
np.median(X_treino)

-0.44850949388572553

In [ ]:
from sklearn.naive_bayes import BernoulliNB

In [ ]:
X_treino_binarizado = np.where(X_treino > np.median(X_treino), 1,0)

In [ ]:
bnb = BernoulliNB()

In [ ]:
bnb.fit(X_treino_binarizado, y_treino)

BernoulliNB()

In [ ]:
predito_Bnb = bnb.predict(X_teste)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dtc = DecisionTreeClassifier(criterion='entropy', random_state=42)

In [ ]:
dtc.fit(X_treino, y_treino)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [ ]:
dtc.feature_importances_

array([0.01778665, 0.01371547, 0.00315951, 0.01889748, 0.01485773,
       0.15333498, 0.20678105, 0.0099271 , 0.0030994 , 0.01373475,
       0.00716366, 0.00077215, 0.        , 0.05357769, 0.        ,
       0.01661967, 0.00924013, 0.        , 0.01178018, 0.00911949,
       0.        , 0.01197541, 0.01560609, 0.        , 0.01440134,
       0.00513946, 0.        , 0.00660354, 0.00718943, 0.        ,
       0.01839729, 0.00893017, 0.23348935, 0.02776301, 0.0181177 ,
       0.03563384, 0.01337186, 0.0198144 ])

In [ ]:
predito_ArvoreDecisao = dtc.predict(X_teste)

In [ ]:
predito_ArvoreDecisao

array([0, 0, 0, ..., 0, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
print(confusion_matrix(y_teste, predito_knn))

[[1245  324]
 [ 264 1272]]


In [ ]:
print(confusion_matrix(y_teste, predito_Bnb))

[[1060  509]
 [ 205 1331]]


In [ ]:
print(confusion_matrix(y_teste, predito_ArvoreDecisao))

[[1274  295]
 [ 271 1265]]


In [ ]:
#accuracy score, make it %, more genral aproach
from sklearn.metrics import accuracy_score

In [ ]:
print(accuracy_score(y_teste, predito_knn))

0.8106280193236715


In [ ]:
print(accuracy_score(y_teste, predito_Bnb))

0.770048309178744


In [ ]:
print(accuracy_score(y_teste, predito_ArvoreDecisao))

0.8177133655394525


In [ ]:
#precision of positive numbers
from sklearn.metrics import precision_score

In [ ]:
print(precision_score(y_teste, predito_knn))

0.7969924812030075


In [ ]:
print(precision_score(y_teste, predito_Bnb))

0.7233695652173913


In [ ]:
print(precision_score(y_teste, predito_ArvoreDecisao))

0.8108974358974359


In [ ]:
#recall, o quao bom ele é em validar corretamente os resultados positivos, ele foca no positivo pra cagar um pouco pro falso
from sklearn.metrics import recall_score

In [ ]:
print(recall_score(y_teste, predito_knn))

0.828125


In [ ]:
print(recall_score(y_teste, predito_Bnb))

0.8665364583333334


In [ ]:
print(recall_score(y_teste, predito_ArvoreDecisao))

0.8235677083333334
